In [104]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.plotting import parallel_coordinates
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.figure_factory as ff
from termcolor import colored
import datetime
import calendar

#### <b>1 <span style='color:#8EDCE6'>|</span> Data Preprocessing </b>

In [115]:
data = pd.read_csv('World_Energy_Overview.csv')
data.head()

Month  Total Fossil Fuels Production  \
0   1973 January                       4.932632   
1  1973 February                       4.729582   
2     1973 March                       4.946902   
3     1973 April                       4.716271   
4       1973 May                       4.956995   

   Nuclear Electric Power Production  Total Renewable Energy Production  \
0                           0.068103                           0.403981   
1                           0.064634                           0.360900   
2                           0.072494                           0.400161   
3                           0.064070                           0.380470   
4                           0.062111                           0.392141   

   Total Primary Energy Production  Primary Energy Imports  \
0                         5.404715                1.173080   
1                         5.155115                1.168005   
2                         5.419556                1.309473   
3                         5.160812                1.085169   
4                         5.411246                1.162804   

   Primary Energy Exports  Primary Energy Net Imports  \
0                0.125781                    1.047299   
1                0.120883                    1.047122   
2                0.139950                    1.169523   
3                0.194185                    0.890984   
4                0.196775                    0.966029   

   Primary Energy Stock Change and Other  Total Fossil Fuels Consumption  \
0                               0.771858                        6.747651   
1                               0.390129                        6.163095   
2                              -0.067640                        6.044647   
3                              -0.110067                        5.493184   
4                              -0.305335                        5.613551   

   Nuclear Electric Power Consumption  Total Renewable Energy Consumption  \
0                            0.068103                            0.403981   
1                            0.064634                            0.360900   
2                            0.072494                            0.400161   
3                            0.064070                            0.380470   
4                            0.062111                            0.392141   

   Total Primary Energy Consumption  
0                          7.223873  
1                          6.592366  
2                          6.521439  
3                          5.941729  
4                          6.071940

In [116]:
data['Year'], data['Month'] = data['Month'].str.split(' ').str
# data.head()

In [117]:
months = {
        'January': '01',
        'February': '02',
        'March': '03',
        'April': '04',
         'May': '05',
         'June': '06',
         'July': '07',
         'August': '08',
         'September': '09',
         'October': '10',
         'November': '11',
         'December': '12'
        }

In [118]:
data2 = data.replace({"Month": months})
data2.head()

Month  Total Fossil Fuels Production  Nuclear Electric Power Production  \
0    01                       4.932632                           0.068103   
1    02                       4.729582                           0.064634   
2    03                       4.946902                           0.072494   
3    04                       4.716271                           0.064070   
4    05                       4.956995                           0.062111   

   Total Renewable Energy Production  Total Primary Energy Production  \
0                           0.403981                         5.404715   
1                           0.360900                         5.155115   
2                           0.400161                         5.419556   
3                           0.380470                         5.160812   
4                           0.392141                         5.411246   

   Primary Energy Imports  Primary Energy Exports  Primary Energy Net Imports  \
0                1.173080                0.125781                    1.047299   
1                1.168005                0.120883                    1.047122   
2                1.309473                0.139950                    1.169523   
3                1.085169                0.194185                    0.890984   
4                1.162804                0.196775                    0.966029   

   Primary Energy Stock Change and Other  Total Fossil Fuels Consumption  \
0                               0.771858                        6.747651   
1                               0.390129                        6.163095   
2                              -0.067640                        6.044647   
3                              -0.110067                        5.493184   
4                              -0.305335                        5.613551   

   Nuclear Electric Power Consumption  Total Renewable Energy Consumption  \
0                            0.068103                            0.403981   
1                            0.064634                            0.360900   
2                            0.072494                            0.400161   
3                            0.064070                            0.380470   
4                            0.062111                            0.392141   

   Total Primary Energy Consumption  Year  
0                          7.223873  1973  
1                          6.592366  1973  
2                          6.521439  1973  
3                          5.941729  1973  
4                          6.071940  1973

In [119]:
data2['Month'] = data2['Month'].map(str)
data2['Year'] = data2['Year'].map(str)
data2

Month  Total Fossil Fuels Production  Nuclear Electric Power Production  \
0      01                       4.932632                           0.068103   
1      02                       4.729582                           0.064634   
2      03                       4.946902                           0.072494   
3      04                       4.716271                           0.064070   
4      05                       4.956995                           0.062111   
..    ...                            ...                                ...   
595    08                       7.047525                           0.718526   
596    09                       6.915201                           0.664673   
597    10                       7.126618                           0.614741   
598    11                       6.875368                           0.647029   
599    12                       6.838495                           0.720583   

     Total Renewable Energy Production  Total Primary Energy Production  \
0                             0.403981                         5.404715   
1                             0.360900                         5.155115   
2                             0.400161                         5.419556   
3                             0.380470                         5.160812   
4                             0.392141                         5.411246   
..                                 ...                              ...   
595                           1.044026                         8.810077   
596                           0.978647                         8.558521   
597                           1.019209                         8.760568   
598                           1.097519                         8.619915   
599                           1.086509                         8.645586   

     Primary Energy Imports  Primary Energy Exports  \
0                  1.173080                0.125781   
1                  1.168005                0.120883   
2                  1.309473                0.139950   
3                  1.085169                0.194185   
4                  1.162804                0.196775   
..                      ...                     ...   
595                1.821828                2.327090   
596                1.702048                2.219831   
597                1.767733                2.322475   
598                1.761697                2.305923   
599                1.796398                2.416155   

     Primary Energy Net Imports  Primary Energy Stock Change and Other  \
0                      1.047299                               0.771858   
1                      1.047122                               0.390129   
2                      1.169523                              -0.067640   
3                      0.890984                              -0.110067   
4                      0.966029                              -0.305335   
..                          ...                                    ...   
595                   -0.505262                               0.225628   
596                   -0.517784                              -0.257997   
597                   -0.554743                              -0.394651   
598                   -0.544226                               0.210202   
599                   -0.619757                               1.054346   

     Total Fossil Fuels Consumption  Nuclear Electric Power Consumption  \
0                          6.747651                            0.068103   
1                          6.163095                            0.064634   
2                          6.044647                            0.072494   
3                          5.493184                            0.064070   
4                          5.613551                            0.062111   
..                              ...                                 ...   
595                        6.755154                            0.718526   
596 

In [120]:
df = data2[:-1]
df

Month  Total Fossil Fuels Production  Nuclear Electric Power Production  \
0      01                       4.932632                           0.068103   
1      02                       4.729582                           0.064634   
2      03                       4.946902                           0.072494   
3      04                       4.716271                           0.064070   
4      05                       4.956995                           0.062111   
..    ...                            ...                                ...   
594    07                       6.921426                           0.718109   
595    08                       7.047525                           0.718526   
596    09                       6.915201                           0.664673   
597    10                       7.126618                           0.614741   
598    11                       6.875368                           0.647029   

     Total Renewable Energy Production  Total Primary Energy Production  \
0                             0.403981                         5.404715   
1                             0.360900                         5.155115   
2                             0.400161                         5.419556   
3                             0.380470                         5.160812   
4                             0.392141                         5.411246   
..                                 ...                              ...   
594                           1.132400                         8.771935   
595                           1.044026                         8.810077   
596                           0.978647                         8.558521   
597                           1.019209                         8.760568   
598                           1.097519                         8.619915   

     Primary Energy Imports  Primary Energy Exports  \
0                  1.173080                0.125781   
1                  1.168005                0.120883   
2                  1.309473                0.139950   
3                  1.085169                0.194185   
4                  1.162804                0.196775   
..                      ...                     ...   
594                1.907862                2.294320   
595                1.821828                2.327090   
596                1.702048                2.219831   
597                1.767733                2.322475   
598                1.761697                2.305923   

     Primary Energy Net Imports  Primary Energy Stock Change and Other  \
0                      1.047299                               0.771858   
1                      1.047122                               0.390129   
2                      1.169523                              -0.067640   
3                      0.890984                              -0.110067   
4                      0.966029                              -0.305335   
..                          ...                                    ...   
594                   -0.386458                               0.199327   
595                   -0.505262                               0.225628   
596                   -0.517784                              -0.257997   
597                   -0.554743                              -0.394651   
598                   -0.544226                               0.210202   

     Total Fossil Fuels Consumption  Nuclear Electric Power Consumption  \
0                          6.747651                            0.068103   
1                          6.163095                            0.064634   
2                          6.044647                            0.072494   
3                          5.493184                            0.064070   
4                          5.613551                            0.062111   
..                              ...                                 ...   
594                        6.736891                            0.718109   
595 

In [121]:
date_1 ='{}-{}'.format(df['Month'].iloc[0], df['Year'].iloc[0])
date_2 = '{}-{}'.format('December', df['Year'].iloc[598])

df.index = pd.date_range(date_1, date_2, freq='M')
df.head()

Month  Total Fossil Fuels Production  \
1973-01-31    01                       4.932632   
1973-02-28    02                       4.729582   
1973-03-31    03                       4.946902   
1973-04-30    04                       4.716271   
1973-05-31    05                       4.956995   

            Nuclear Electric Power Production  \
1973-01-31                           0.068103   
1973-02-28                           0.064634   
1973-03-31                           0.072494   
1973-04-30                           0.064070   
1973-05-31                           0.062111   

            Total Renewable Energy Production  \
1973-01-31                           0.403981   
1973-02-28                           0.360900   
1973-03-31                           0.400161   
1973-04-30                           0.380470   
1973-05-31                           0.392141   

            Total Primary Energy Production  Primary Energy Imports  \
1973-01-31                         5.404715                1.173080   
1973-02-28                         5.155115                1.168005   
1973-03-31                         5.419556                1.309473   
1973-04-30                         5.160812                1.085169   
1973-05-31                         5.411246                1.162804   

            Primary Energy Exports  Primary Energy Net Imports  \
1973-01-31                0.125781                    1.047299   
1973-02-28                0.120883                    1.047122   
1973-03-31                0.139950                    1.169523   
1973-04-30                0.194185                    0.890984   
1973-05-31                0.196775                    0.966029   

            Primary Energy Stock Change and Other  \
1973-01-31                               0.771858   
1973-02-28                               0.390129   
1973-03-31                              -0.067640   
1973-04-30                              -0.110067   
1973-05-31                              -0.305335   

            Total Fossil Fuels Consumption  \
1973-01-31                        6.747651   
1973-02-28                        6.163095   
1973-03-31                        6.044647   
1973-04-30                        5.493184   
1973-05-31                        5.613551   

            Nuclear Electric Power Consumption  \
1973-01-31                            0.068103   
1973-02-28                            0.064634   
1973-03-31                            0.072494   
1973-04-30                            0.064070   
1973-05-31                            0.062111   

            Total Renewable Energy Consumption  \
1973-01-31                            0.403981   
1973-02-28                            0.360900   
1973-03-31                            0.400161   
1973-04-30                            0.380470   
1973-05-31                            0.392141   

            Total Primary Energy Consumption  Year  
1973-01-31                          7.223873  1973  
1973-02-28                          6.592366  1973  
1973-03-31                          6.521439  1973  
1973-04-30                          5.941729  1973  
1973-05-31                          6.071940  1973

In [122]:
data3 = df.drop(['Year', 'Month'], axis=1)
data3 = data3.rename_axis('Date')
data3.head()

Total Fossil Fuels Production  Nuclear Electric Power Production  \
Date                                                                           
1973-01-31                       4.932632                           0.068103   
1973-02-28                       4.729582                           0.064634   
1973-03-31                       4.946902                           0.072494   
1973-04-30                       4.716271                           0.064070   
1973-05-31                       4.956995                           0.062111   

            Total Renewable Energy Production  \
Date                                            
1973-01-31                           0.403981   
1973-02-28                           0.360900   
1973-03-31                           0.400161   
1973-04-30                           0.380470   
1973-05-31                           0.392141   

            Total Primary Energy Production  Primary Energy Imports  \
Date                                                                  
1973-01-31                         5.404715                1.173080   
1973-02-28                         5.155115                1.168005   
1973-03-31                         5.419556                1.309473   
1973-04-30                         5.160812                1.085169   
1973-05-31                         5.411246                1.162804   

            Primary Energy Exports  Primary Energy Net Imports  \
Date                                                             
1973-01-31                0.125781                    1.047299   
1973-02-28                0.120883                    1.047122   
1973-03-31                0.139950                    1.169523   
1973-04-30                0.194185                    0.890984   
1973-05-31                0.196775                    0.966029   

            Primary Energy Stock Change and Other  \
Date                                                
1973-01-31                               0.771858   
1973-02-28                               0.390129   
1973-03-31                              -0.067640   
1973-04-30                              -0.110067   
1973-05-31                              -0.305335   

            Total Fossil Fuels Consumption  \
Date                                         
1973-01-31                        6.747651   
1973-02-28                        6.163095   
1973-03-31                        6.044647   
1973-04-30                        5.493184   
1973-05-31                        5.613551   

            Nuclear Electric Power Consumption  \
Date                                             
1973-01-31                            0.068103   
1973-02-28                            0.064634   
1973-03-31                            0.072494   
1973-04-30                            0.064070   
1973-05-31                            0.062111   

            Total Renewable Energy Consumption  \
Date                                             
1973-01-31                            0.403981   
1973-02-28                            0.360900   
1973-03-31                            0.400161   
1973-04-30                            0.380470   
1973-05-31                            0.392141   

            Total Primary Energy Consumption  
Date                                          
1973-01-31                          7.223873  
1973-02-28                          6.592366  
1973-03-31                          6.521439  
1973-04-30                          5.941729  
1973-05-31                          6.071940

In [123]:
total_production0 = data3.filter(['Total Primary Energy Production'], axis=1)
total_production = total_production0.rename(columns={'Total Primary Energy Production':'Total_Production'})
total_production.head()

Total_Production
Date                        
1973-01-31          5.404715
1973-02-28          5.155115
1973-03-31          5.419556
1973-04-30          5.160812
1973-05-31          5.411246

In [124]:
fig = px.line(total_production, x = total_production.index, y= total_production.Total_Production,labels={
                     "Month": "Month",
                     "value": "Production Rate"}, title='Monthly Poroduction Rate of World',width=1500, height=800)
fig.show()

In [125]:
from statsmodels.tsa.seasonal import seasonal_decompose
results = seasonal_decompose(total_production['Total_Production'])

fig_1 = px.line(y=results.observed, x=results.observed.index, title='Observed',width=1500)
fig_1.show()

In [126]:
fig_2 = px.line(y=results.trend, x=results.trend.index, title='Trend',width=1500)
fig_2.show()

In [127]:
fig_2 = px.line(y=results.seasonal, x=results.seasonal.index, title='Seasonality',width=1500)
fig_2.show()

In [128]:
fig_2 = px.line(y=results.resid, x=results.resid.index, title='Residual',width=1500)
fig_2.show()

In [129]:
train = total_production[:-20]
test = total_production[-20:]
print(train.shape, test.shape)

(579, 1) (20, 1)


#### <b> 2 <span style='color:#8EDCE6'>|</span> Auto Regression Model </b>

In [130]:
from statsmodels.tsa.ar_model import AutoReg

In [131]:
autoreg_model = AutoReg(train, lags=10).fit()
print(autoreg_model.summary())

                            AutoReg Model Results                             
Dep. Variable:       Total_Production   No. Observations:                  579
Model:                    AutoReg(10)   Log Likelihood                  85.050
Method:               Conditional MLE   S.D. of innovations              0.208
Date:                Sat, 22 Apr 2023   AIC                           -146.100
Time:                        16:12:19   BIC                            -93.974
Sample:                    11-30-1973   HQIC                          -125.760
                         - 03-31-2021                                         
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                    0.0190      0.071      0.267      0.789      -0.120       0.158
Total_Production.L1      0.2684      0.042      6.354      0.000       0.186       0.351
Total_Produc

In [132]:
pred_auto = autoreg_model.predict(start = len(train), end = len(total_production)-1, dynamic=False)
# print(pred_auto)

In [133]:
fig = px.line(test['Total_Production'], width=1500)
fig.add_scatter(x=test.index, y=pred_auto, name='Predictions')
fig.show()

In [134]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, accuracy_score

print('Mean Squared Error: ', mean_squared_error(test['Total_Production'], pred_auto))

Mean Squared Error:  0.3566408009962111


#### <b> 3 <span style='color:#8EDCE6'>|</span> Arima Model </b>

In [135]:
from pmdarima import auto_arima
import warnings
warnings.filterwarnings("ignore")

In [136]:
stepwise_fit = auto_arima(total_production['Total_Production'], trace=True, suppress_warnings=True)
stepwise_fit.summary()

Performing stepwise search to minimize aic
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=-49.866, Time=0.43 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=320.634, Time=0.04 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=21.685, Time=0.05 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-23.479, Time=0.13 sec
 ARIMA(0,1,0)(0,0,0)[0]             : AIC=318.808, Time=0.04 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=-49.992, Time=0.27 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=-44.048, Time=0.14 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=-50.918, Time=0.15 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=-51.405, Time=0.19 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=-29.629, Time=0.07 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=-51.313, Time=0.23 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=-28.882, Time=0.10 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=-86.425, Time=0.56 sec
 ARIMA(4,1,2)(0,0,0)[0] intercept   : AIC=-143.118, Time=0.70 sec
 ARIMA(4,1,1)(0,0,0)[0] intercept   : AIC=-139.

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results                                
==============================================================================
Dep. Variable:                      y   No. Observations:                  599
Model:               SARIMAX(3, 1, 3)   Log Likelihood                 151.658
Date:                Sat, 22 Apr 2023   AIC                           -287.317
Time:                        16:12:28   BIC                           -252.168
Sample:                    01-31-1973   HQIC                          -273.632
                         - 11-30-2022                                         
Covariance Type:                  opg                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept      0.0182      0.008      2.301      0.021       0.003       0.034
ar.L1         -1.4432      0.054    -26.530      0.000      -1.550      -1.337
ar.L2         -0.5066      0.094     -5.377      0.000      -0.691      -0.322
ar.L3          0.2809      0.054      5.188      0.000       0.175       0.387
ma.L1          0.8970      0.044     20.470      0.000       0.811       0.983
ma.L2         -0.3331      0.059     -5.667      0.000      -0.448      -0.218
ma.L3         -0.7404      0.038    -19.624      0.000      -0.814      -0.666
sigma2         0.0380      0.002     21.927      0.000       0.035       0.041
===================================================================================
Ljung-Box (L1) (Q):                   0.46   Jarque-Bera (JB):               262.75
Prob(Q):                              0.50   Prob(JB):                         0.00
Heteroskedasticity (H):               1.51   Skew:                            -0.76
Prob(H) (two-sided):                  0.00   Kurtosis:                         5.87
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

In [137]:
import statsmodels.api as sm

arima_model = sm.tsa.arima.ARIMA(train['Total_Production'], order=(3, 1, 3))
arima_model = arima_model.fit()
arima_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results                                
==============================================================================
Dep. Variable:       Total_Production   No. Observations:                  579
Model:                 ARIMA(3, 1, 3)   Log Likelihood                 156.147
Date:                Sat, 22 Apr 2023   AIC                           -298.293
Time:                        16:12:29   BIC                           -267.776
Sample:                    01-31-1973   HQIC                          -286.394
                         - 03-31-2021                                         
Covariance Type:                  opg                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1         -1.5049      0.050    -29.809      0.000      -1.604      -1.406
ar.L2         -0.6070      0.088     -6.913      0.000      -0.779      -0.435
ar.L3          0.2266      0.051      4.465      0.000       0.127       0.326
ma.L1          0.9869      0.066     14.903      0.000       0.857       1.117
ma.L2         -0.2470      0.069     -3.585      0.000      -0.382      -0.112
ma.L3         -0.7265      0.063    -11.519      0.000      -0.850      -0.603
sigma2         0.0334      0.002     13.999      0.000       0.029       0.038
===================================================================================
Ljung-Box (L1) (Q):                   0.11   Jarque-Bera (JB):               299.68
Prob(Q):                              0.75   Prob(JB):                         0.00
Heteroskedasticity (H):               1.52   Skew:                            -0.77
Prob(H) (two-sided):                  0.00   Kurtosis:                         6.17
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

In [138]:
start = len(train)
end = len(train) + len(test) - 1
pred_arima = arima_model.predict(start=start, end=end, type='levels')
# print(prediction)

In [139]:
fig = px.line(test['Total_Production'], width=1500)
fig.add_scatter(x=test.index, y=pred_arima, name='Predictions')
fig.show()

In [140]:
print('Mean Squared Error: ', mean_squared_error(test['Total_Production'], pred_arima))

Mean Squared Error:  0.3838041979700952


In [141]:
train_l = total_production[:570]
test_l = total_production[570:]

In [142]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [143]:
scaler.fit(train)
scaled_train = scaler.transform(train)
scaled_test = scaler.transform(test)

In [144]:
from keras.preprocessing.sequence import TimeseriesGenerator

In [145]:
n_input = 3
n_features = 1
generator = TimeseriesGenerator(scaled_train, scaled_train, length=n_input, batch_size=1)

In [146]:
n_input = 12
generator = TimeseriesGenerator(scaled_train, scaled_train, length=n_input, batch_size=1)

In [147]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

In [148]:
# define model
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(n_input, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [149]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 100)               40800     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 40,901
Trainable params: 40,901
Non-trainable params: 0
_________________________________________________________________


In [150]:
# fit model
model.fit(generator,epochs=100)

Epoch 1/100
567/567 [==============================] - 3s 3ms/step - loss: 0.0117
Epoch 2/100
567/567 [==============================] - 2s 3ms/step - loss: 0.0048
Epoch 3/100
567/567 [==============================] - 2s 3ms/step - loss: 0.0039
Epoch 4/100
567/567 [==============================] - 2s 3ms/step - loss: 0.0034
Epoch 5/100
567/567 [==============================] - 2s 3ms/step - loss: 0.0036
Epoch 6/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0034
Epoch 7/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0034
Epoch 8/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0036
Epoch 9/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0033
Epoch 10/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0032
Epoch 11/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0032
Epoch 12/100
567/567 [==============================] - 2s 4ms/step - loss: 0.0030
Epoch 13/100


In [151]:
loss_per_epoch = model.history.history['loss']
fig = px.line(loss_per_epoch).show()

In [152]:
last_train_batch = scaled_train[-12:]
last_train_batch = last_train_batch.reshape((1, n_input, n_features))

In [153]:
model.predict(last_train_batch)

1/1 [==============================] - 0s 187ms/step


array([[0.86121476]], dtype=float32)

In [154]:
test_predictions = []

first_eval_batch = scaled_train[-n_input:]
current_batch = first_eval_batch.reshape((1, n_input, n_features))

for i in range(len(test)):
    
    # get the prediction value for the first batch
    current_pred = model.predict(current_batch)[0]
    
    # append the prediction into the array
    test_predictions.append(current_pred) 
    
    # use the prediction to update the batch and remove the first value
    current_batch = np.append(current_batch[:,1:,:],[[current_pred]],axis=1)

1/1 [==============================] - 0s 32ms/step


In [155]:
test_predictions

[array([0.86121476], dtype=float32),
 array([0.83245933], dtype=float32),
 array([0.8694246], dtype=float32),
 array([0.91329396], dtype=float32),
 array([0.9470625], dtype=float32),
 array([0.94390726], dtype=float32),
 array([0.960631], dtype=float32),
 array([0.98129714], dtype=float32),
 array([1.054083], dtype=float32),
 array([1.1193308], dtype=float32),
 array([0.76469374], dtype=float32),
 array([1.081523], dtype=float32),
 array([1.0561452], dtype=float32),
 array([1.0183706], dtype=float32),
 array([1.0469966], dtype=float32),
 array([1.0495499], dtype=float32),
 array([1.050457], dtype=float32),
 array([1.0362124], dtype=float32),
 array([1.0178951], dtype=float32),
 array([0.9942225], dtype=float32)]

In [156]:
test

Total_Production
Date                        
2021-04-30          8.017904
2021-05-31          8.400589
2021-06-30          8.170063
2021-07-31          8.357812
2021-08-31          8.421374
2021-09-30          8.066687
2021-10-31          8.371038
2021-11-30          8.348218
2021-12-31          8.672236
2022-01-31          8.531384
2022-02-28          7.765558
2022-03-31          8.679065
2022-04-30          8.308820
2022-05-31          8.725353
2022-06-30          8.570749
2022-07-31          8.771935
2022-08-31          8.810077
2022-09-30          8.558521
2022-10-31          8.760568
2022-11-30          8.619915

In [157]:
true_predictions = scaler.inverse_transform(test_predictions)

In [158]:
test['Predictions'] = true_predictions
test

Total_Production  Predictions
Date                                     
2021-04-30          8.017904     8.159312
2021-05-31          8.400589     8.030679
2021-06-30          8.170063     8.196037
2021-07-31          8.357812     8.392280
2021-08-31          8.421374     8.543338
2021-09-30          8.066687     8.529224
2021-10-31          8.371038     8.604035
2021-11-30          8.348218     8.696482
2021-12-31          8.672236     9.022078
2022-01-31          8.531384     9.313954
2022-02-28          7.765558     7.727540
2022-03-31          8.679065     9.144826
2022-04-30          8.308820     9.031303
2022-05-31          8.725353     8.862324
2022-06-30          8.570749     8.990378
2022-07-31          8.771935     9.001800
2022-08-31          8.810077     9.005858
2022-09-30          8.558521     8.942137
2022-10-31          8.760568     8.860197
2022-11-30          8.619915     8.754301

In [159]:
# test.plot(figsize=(14,5))

fig = px.line(test).show()

In [160]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, accuracy_score
from math import sqrt
rmse=sqrt(mean_squared_error(test['Total_Production'],test['Predictions']))
r2 = (r2_score(test['Total_Production'], test['Predictions']))
print(rmse)
print(r2)

0.35351186429064174
-0.6687586684531786
